sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- echo "Cloudboost flow-service"
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
install:
- npm install
after_success:
# Build Docker Images
- docker build -t cloudboost/flow-service:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/flow-service:latest .
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
- docker push cloudboost/flow-service:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/flow-service:latest
- git clone https://github.com/CloudBoost/kube-cred.git
- cd kube-cred
- openssl enc -in config.enc -out config -d -aes256 -k $KUBE_ENC
- mkdir ~/.kube
- mv config ~/.kube/
- kubectl rolling-update cloudboost-flow-service --image=cloudboost/flow-service:latest --image-pull-policy=Always
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW